---
abstract: 'Command line tool for print Wikidata item.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0
  File::Spec::Functions: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Wikidata-Print
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0
  Getopt::Std: 0
  Unicode::UTF8: 0
  Wikibase::API: 0.04
  Wikibase::Datatype::Print::Item: 0.12
  Wikibase::Datatype::Print::Lexeme: 0.12
  Wikibase::Datatype::Print::Property: 0.12
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/App-Wikidata-Print/issues
  homepage: https://github.com/michal-josef-spacek/App-Wikidata-Print
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/App-Wikidata-Print
version: '0.02'
